### ISSUE TITLE
EPIC : Initial Django Setup

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/wavey-blog#1]
As a **Developer** I can **setup Django and deploy site** so that **I can develop the Site**

## Tasks
- [ ] Install Django and supporting Libraries
- [ ] Create Apps
- [ ] Create secret keys and place in .env
- [ ] Deploy to Heroku
