### ISSUE TITLE
User Story : User can edit their profile

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/wavey-blog#15]
As a **User** I can **edit my profile** so that **I can keep my information up to date**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged into my account 
	**When** I am viewing my profile
	**Then** I should be able to edit those details

- Acceptance Criteria 2
	**Given** that I am logged into my account
	**When** I click on the edit profile button
	**Then** I am taken to the relevant page to do so

- Acceptance Criteria 3
	**Given** that I am not logged in to my account
	**When** I go to any profile page
	**Then** I do not see the edit profile button

- Acceptance Criteria 4
	**Given** that I am not logged in to my account 
	**When** I try and go directly to mine or somebody's edit profile page through their URL
	**Then** I get redirected to the login page

## Tasks
- [ ] Develop a way for Users to edit their own profile
- [ ] Create a page where profiles can be edited
- [ ] Add a button to a Users profile that only shows when they are logged in
- [ ] Prevent Users from accessing other Users' edit profile page
- [ ] Prevent Users accessing their own edit profile page when not logged in
