### ISSUE TITLE
User Story : Create a Post

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/wavey-blog#17]
As a **User** I can **create a post** so that **I can share my knowledge with others**

## Acceptance Criteria

- Acceptance Criteria 1
	**Given** that I am User logged in to my account
	**When** I go to the home page
	**Then** I have to option create a post

- Acceptance Criteria 2
	**Given** that I have created a post as a logged-in User
	**When** I save that post
	**Then** it can be viewed by other Users on the site

## Tasks
- [ ] Develop a form for a User to create and submit a post
- [ ] Develop a model for the post
- [ ] Create a validation to make sure information included in post is correct
- [ ] Connect the form to post model to create a new record
- [ ] Develop the method to create a record once the post has been created
