### ISSUE TITLE
User Story : Delete a Post

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/wavey-blog#20]
As a **User** I can **delete one of my posts** so that **I have control over anything i have shared**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered User with posts created
	**When** I navigate to a post I would like to delete
	**Then** I have the option to do so

- Acceptance Criteria 2
	**Given** that  I am a registered User with posts created
	**When** I have selected the post I wish to delete
	**Then** I am greeted with a confirmation request before the post is deleted

- Acceptance Criteria 3
	**Given** that  I am a registered User with posts created
	**When** I have confirmed the post I wish to delete
	**Then** the post is deleted from my account

- Acceptance Criteria 4
	**Given** that I am an unregistered User or not logged in 
	**When** I am on a post 
	**Then** I do not have the option to delete a post

## Tasks
- [ ] Develop a delete post button that shows on the full post page when the logged in User is the post author
- [ ] Develop a confirmation window that appears once the delete button has been pressed
- [ ] Develop the code to delete this post is the above criteria is met
- [ ] Prevent unregistered users or non-authors of a post from seeing the delete post button
