### ISSUE TITLE
EPIC : Site Owner Objectives

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/wavey-blog#4]
As a **Site Owner** I can **use the Site to attract sponsorship** so that ***the Site can make a profit*

## Tasks
- [ ] Capture user details
- [ ] Make initial post database available to all visitors to site
- [ ] Fully responsive site - accessible on multiple devices
