### ISSUE TITLE
EPIC - Post interaction

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/wavey-blog#8]
As a **User** I can **interact with a post** so that **I can provide feedback and interact with the commuinity**

## Potential User Stories
- [ ] Be able to add comments to a post
- [ ] Notification if somebody makes a comment on your post
- [ ] Notification if somebody replies to a comment
- [ ] Report inappropriate comments to admin
- [ ] Be able to control notifications of posts/comments
