### ISSUE TITLE
USER STORY : Django Setup

### ISSUE THREAD

**Issue by mattcooperdev** [YesCoops/wavey-blog#9]
As a **developer** I can **install Django and setup the necessary libraries** so that **I am ready to start development**

## Tasks
- [x]  Install Django
- [x] Install dj_database_url psycopg2
- [x] Install dj3-cloudinary-storage
- [x] Create a requirements.txt file
- [x] Create the Django project 
- [x] Create the first app – called posts and add it to the installed apps in the settings.py
